default_url_options:
  host: '520c-220-147-214-245.ngrok-free.app'
line_callback_url: 
  url: 'https://520c-220-147-214-245.ngrok-free.app/oauth/callback?provider=line'
redis:
  url: 'redis://redis:6379'